### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by xialuo0511** [fuqiuluo/unidbg-fetch-qsign#113]
在自己的电脑上搭建也出现过
Exception in thread "main" java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)

**Comment by fuqiuluo** [comment]
端口被占用了？

**Comment by xialuo0511** [comment]
> 端口被占用了？

排查出问题了，谢谢

**Comment by xialuo0511** [comment]
> 

但是为什么有时候我搭建的机器人api连接的上，但运行一段时间后直接发信息无响应了，约2分钟的样子，排查了一个星期没找到原因

**Comment by arnann** [comment]
> > 端口被占用了？
> 
> 排查出问题了，谢谢

这个是怎么解决的呀，我现在也有这个问题

**Comment by xialuo0511** [comment]
> > > 端口被占用了？
> > 
> > 
> > 排查出问题了，谢谢
> 
> 这个是怎么解决的呀，我现在也有这个问题

一个是传入的参数有误，一个是端口被其他占用了，这俩个排查一下，排查不出的话就重装
