### ISSUE TITLE
这个报错。。怎么解决

### ISSUE THREAD

**Issue by qanderer** [fuqiuluo/unidbg-fetch-qsign#116]
测试环境如下
```
腾讯云轻量服务器
Ubuntu22.04.2
2h2g
机器人路径:root/Miao-Yunza
node版本18.16.1
```
报错代码如下
```
/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/composer.js:69
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^
YAMLParseError: Map keys must be unique at line 26, column 16:

sign_api_addr: 
               ^
    at Composer.onError (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveBlockMap (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/resolve-block-map.js:61:13)
    at resolveCollection (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/compose-collection.js:13:27)
    at Object.composeCollection (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/compose-collection.js:47:16)
    at Object.composeNode (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/compose-node.js:31:38)    at Object.composeDoc (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/compose-doc.js:33:23)
    at Composer.next (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/composer.js:149:40)
    at next (<anonymous>)
    at Composer.compose (/root/Miao-Yunzai/node_modules/.store/yaml@2.3.1/node_modules/yaml/dist/compose/composer.js:131:25)
    at compose.next (<anonymous>) {
  code: 'DUPLICATE_KEY',
  pos: [ 386, 387 ],
  linePos: [ { line: 26, col: 16 }, { line: 27, col: 1 } ]
}

Node.js v18.16.1
```

**Comment by AIxPha** [comment]
这是你配置文件写错了
应该去喵崽项目提
和Sign没关系

示例
sign_api_addr: http://127.0.0.1:端口/sign

[完整bot.yaml示例](https://github.com/fuqiuluo/unidbg-fetch-qsign/files/11995729/bot.log)
