### ISSUE TITLE
Field 'autoRegister' is required for type with serial name 'moe.fuqiuluo.comm.QSignConfig'

### ISSUE THREAD

**Issue by xiaoyv404** [fuqiuluo/unidbg-fetch-qsign#127]
unidbg-fetch-qsign版本: 1.1.4
txlib版本: 8.9.63
Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'autoRegister' is required for type with serial name 'moe.fuqiuluo.comm.QSignConfig', but it was missing at path: $
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:93)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
        at MainKt.main(Main.kt:79)
Caused by: kotlinx.serialization.MissingFieldException: Field 'autoRegister' is required for type with serial name 'moe.fuqiuluo.comm.QSignConfig', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at moe.fuqiuluo.comm.QSignConfig.<init>(QSignConfig.kt:42)
        at moe.fuqiuluo.comm.QSignConfig$$serializer.deserialize(QSignConfig.kt:42)
        at moe.fuqiuluo.comm.QSignConfig$$serializer.deserialize(QSignConfig.kt:42)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        ... 2 more

**Comment by xiaoyv404** [comment]
我的问题，直接拿1.1.3的config覆盖了
