### ISSUE TITLE
【报错】docker openjdk 11 18 运行 1.1.4 qsign

### ISSUE THREAD

**Issue by CatOverrun** [fuqiuluo/unidbg-fetch-qsign#129]
<details><summary>Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON</summary><p>
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
        at com.tencent.mobileqq.dt.model.FEBound.initAssertConfig(FEBound.java:89)
        at MainKt.main(Main.kt:47)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
        at com.tencent.mobileqq.dt.model.FEBound.initAssertConfig(FEBound.java:89)
        at MainKt.main(Main.kt:47)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
        at com.tencent.mobileqq.dt.model.FEBound.initAssertConfig(FEBound.java:89)
        at MainKt.main(Main.kt:47)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
        at com.tencent.mobileqq.dt.model.FEBound.initAssertConfig(FEBound.java:89)
        at MainKt.main(Main.kt:47)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
</p></details>

**Comment by CatOverrun** [comment]
测试环境: ubuntu 20.04
docker 24.0.2
image: openjdk: 11.0-jdk,openjdk: 18.0-jdk, openjdk: 19-jdk
均报错上面的信息。

**Comment by CatOverrun** [comment]
应该为tcp上传时文件丢失，重新部署了一次qsign，不再报这个错误。
