### ISSUE TITLE
1.1.5 GLIBC 找不到指定版本

### ISSUE THREAD

**Issue by SuperKenVery** [fuqiuluo/unidbg-fetch-qsign#136]
使用docker运行（openjdk:11.0-jdk)
aarch64
```
java.lang.UnsatisfiedLinkError: /tmp/nativelib-loader_6355469713984926089/libunicorn.so: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/na
tivelib-loader_6355469713984926089/libunicorn.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:348)
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:139)
        at com.github.unidbg.arm.backend.Unicorn2Factory.<clinit>(Unicorn2Factory.java:11)
        at moe.fuqiuluo.unidbg.vm.AndroidVM.<init>(AndroidVM.kt:19)
        at moe.fuqiuluo.unidbg.QSecVM.<init>(QSecVm.kt:20)
        at moe.fuqiuluo.unidbg.session.Session.<init>(Session.kt:13)
        at moe.fuqiuluo.unidbg.session.SessionManager.register(SessionManager.kt:19)
        at moe.fuqiuluo.api.RegisterKt$register$1.invokeSuspend(register.kt:26)
...
```

**Comment by fuqiuluo** [comment]
linux环境缺漏，打开你的docker控制台

1. 安装make
```shell
wget http://ftp.gnu.org/gnu/make/make-4.3.tar.gz
tar xf make-4.3.tar.gz
cd make-4.3/
./configure
make
make install
make -v
/usr/local/bin/make -v
whereis make
cd /usr/bin/
mv make make.bak
ln -sv /usr/local/bin/make /usr/bin/make
make -v
```
2. 安装gcc
```shell
yum -y install centos-release-scl
yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-binutils
scl enable devtoolset-8 bash
echo “source /opt/rh/devtoolset-8/enable” >>/etc/profile
```
3. 安装gdb
```shell
yum install -y gdb
wget http://ftp.gnu.org/gnu/gdb/gdb-7.8.tar.gz
tar -zxvf gdb-7.8.tar.gz
chown -R root.root gdb-7.8
cd gdb-7.8
mkdir build
cd build
../configure –prefix=/usr
make install
gdb -v
```
4. 安装glibc

查看现在的glibc版本 `strings /lib64/libc.so.6 | grep GLIBC`

```shell
wget http://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.gz
tar -zxvf glibc-2.34.tar.gz
cd glibc-2.34
mkdir build;
cd build
../configure –prefix=/usr –disable-profile –enable-add-ons –with-headers=/usr/include –with-binutils=/usr/bin –disable-sanity-checks –disable-werror
make -j 8
make install
```

Reference: https://www.azurew.com/linux/10574.html

**Comment by fuqiuluo** [comment]
从差不多的设备抠一个过去应该也可以

**Comment by SuperKenVery** [comment]
感谢您的回复！

如果是这样，您是否应该更新一下README中的docker-compose部署教程呢？因为我就是照着那个来的 :rofl:

**Comment by fuqiuluo** [comment]
我不会，你可以pr
