### ISSUE TITLE
旧配置文件含有reload_interval会导致1.1.6启动报错

### ISSUE THREAD

**Issue by XZhouQD** [fuqiuluo/unidbg-fetch-qsign#149]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。

RT，建议写到release note里作为一个break change提示吧

**Comment by BennettChina** [comment]
我来放下报错日志吧，配置向后兼容还是没做好啊，建议发布 release 前用低版本配置做个测试。

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 123: Encountered an unknown key 'reload_interval' at path: $.autoRegister
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....
  "auto_register": true,
  "reload_interval": 40,
  "prot.....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:579)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:254)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:240)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:175)
	at moe.fuqiuluo.comm.QSignConfig$$serializer.deserialize(QSignConfig.kt:42)
	at moe.fuqiuluo.comm.QSignConfig$$serializer.deserialize(QSignConfig.kt:42)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at MainKt.main(Main.kt:80)
```

**Comment by BennettChina** [comment]
<img width="745" alt="image" src="https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/48208644/85f77948-22de-483a-9090-77d73b96457e">


应该是要这样改的，按配置创建的 `Json` 返回值未被接收使用，以下是我查资料查到的使用方式：

```kotlin
val jsonString="""{"name":"kotlinx.serialization","language":"Kotlin"}"""
val data = Json{ignoreUnknownKeys = true}.decodeFromString<Project>(jsonString)
```
