### ISSUE TITLE
1.1版本签名服务器报错崩溃

### ISSUE THREAD

**Issue by luosheng520qaq** [fuqiuluo/unidbg-fetch-qsign#158]
Program: E:\aila\gocqapi\API\qsign_oneclick_windows\jre8\bin\java.exe
File: C:/msys64/home/Banny/git/unicorn/qemu/memory.c, Line 1329

Expression: subregion->container == mr
Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalStateException: running
        at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:352)
        at com.github.unidbg.thread.Function64.run(Function64.java:39)
        at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
        at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
        at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
        at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
        at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
        at com.github.unidbg.Module.emulateFunction(Module.java:163)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:52)
        at com.tencent.mobileqq.channel.ChannelManager.onNativeReceive(ChannelManager.kt:24)
        at moe.fuqiuluo.unidbg.env.QSecJni$callVoidMethodV$1.onReceive(QSecJni.kt:75)
        at moe.fuqiuluo.net.Handler.submitPacket(PacketHandler.kt:56)
        at moe.fuqiuluo.net.PacketHandler.invoke(PacketHandler.kt:86)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1$1.invoke(SimpleClient.kt:58)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1$1.invoke(SimpleClient.kt:57)
        at moe.fuqiuluo.net.DecoderKt.decodePacket(Decoder.kt:85)
        at moe.fuqiuluo.net.DecoderKt.decode(Decoder.kt:56)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1.invokeSuspend(SimpleClient.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(selector), StandaloneCoroutine{Cancelling}@38873703, Dispatchers.IO]

**Comment by fuqiuluo** [comment]
更换新版本呢？旧版本不维护了
