### ISSUE TITLE
java.lang.IllegalStateException: This mutex is not locked

### ISSUE THREAD

**Issue by EricDeng1001** [fuqiuluo/unidbg-fetch-qsign#169]
遇到一个unlock未被lock的锁的问题，不影响使用，但是报错了。
```
  20:20:23 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  20:20:23 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.8 (arch: 64)
  20:20:23 [INFO] https://github.com/iTXTech/mirai-console-loader
  20:20:23 [INFO] This program is licensed under GNU AGPL v3
  20:20:24 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  20:20:24 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0
  20:20:26 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0
  20:20:27 [INFO] Verifying "net.mamoe:mirai-core-all" v2.15.0
  20:20:28 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
2023-07-27 20:20:29 I/main: Starting mirai-console...
2023-07-27 20:20:29 I/main:

===================================[ Mirai console 2.15.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-07-27 20:20:29 I/main: Backend: version 2.15.0, built on 2023-07-10 20:57:17.
2023-07-27 20:20:29 I/main: Frontend Terminal: version 2.15.0, provided by Mamoe Technologies
2023-07-27 20:20:29 I/main: Welcome to visit https://mirai.mamoe.net/
2023-07-27 20:20:31 I/plugin: Successfully loaded plugin MercariMirai v0.1.0
2023-07-27 20:20:31 I/fix-protocol-version: 协议版本检查更新...
2023-07-27 20:20:31 I/fix-protocol-version: ANDROID_PHONE load from file:///root/MercariMirai/android_phone.json
2023-07-27 20:20:31 I/fix-protocol-version: ANDROID_PAD load from file:///root/MercariMirai/android_pad.json
2023-07-27 20:20:31 I/fix-protocol-version: 注册服务...
2023-07-27 20:20:31 I/fix-protocol-version: 服务配置文件:
 file:///root/MercariMirai/KFCFactory.json
2023-07-27 20:20:31 I/plugin: Successfully loaded plugin fix-protocol-version v1.9.10
2023-07-27 20:20:31 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-07-27 20:20:31 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-07-27 20:20:31 I/MercariMirai: 加载配置
2023-07-27 20:20:31 I/MercariMirai: 开始初始化机器人
2023-07-27 20:20:31 I/fix-protocol-version: 当前各登录协议版本日期:
ANDROID_PHONE  8.9.63.11390  2023-05-26T02:46:18Z
ANDROID_PAD    8.9.63.11390  2023-05-26T02:46:18Z
ANDROID_WATCH  2.0.8         2019-06-03T12:25:31Z
IPAD           8.9.50.611    2023-02-16T07:10:14Z
MACOS          6.8.2.21241   2022-03-14T03:11:35Z

2023-07-27 20:20:31 I/fix-protocol-version: 当前签名服务配置信息:
v8.9.63 by fuqiuluo/unidbg-fetch-qsign from http://127.0.0.1:8080

2023-07-27 20:20:31 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-07-27 20:20:31 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-07-27 20:20:31 I/main: 3 plugin(s) enabled.
2023-07-27 20:20:31 I/main: Auto-login 1810825454, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-07-27 20:20:32 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///root/MercariMirai/KFCFactory.json)
2023-07-27 20:20:32 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-07-27 20:20:32 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-07-27 20:20:32 W/EncryptService.alert: Service details:
2023-07-27 20:20:32 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-07-27 20:20:32 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.9.10.mirai2.jar}
2023-07-27 20:20:32 W/EncryptService.alert:   `- Source: file:/root/MercariMirai/plugins/fix-protocol-version-1.9.10.mirai2.jar
2023-07-27 20:20:32 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/root/MercariMirai/plugins/fix-protocol-version-1.9.10.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.9.10.mirai2.jar}
 <no principals>
 java.security.Permissions@23e2c1ca (
 ("java.io.FilePermission" "/root/MercariMirai/plugins/fix-protocol-version-1.9.10.mirai2.jar" "read")
)


2023-07-27 20:20:32 I/KFCFactory: ANDROID_PHONE(8.9.63) server type: fuqiuluo/unidbg-fetch-qsign, file:///root/MercariMirai/KFCFactory.json
2023-07-27 20:20:32 I/KFCFactory: unidbg-fetch-qsign by http://127.0.0.1:8080 about
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.7",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
            "version": "8.9.63",
            "code": "4194"
        }
    }
}
2023-07-27 20:20:33 I/UnidbgFetchQsign: Bot(1810825454) initialize by http://127.0.0.1:8080
2023-07-27 20:20:41 I/me.ericdeng.infra.QQPushServiceImpl: 正在等待主环境实例化bot...
2023-07-27 20:20:46 I/UnidbgFetchQsign: Bot(1810825454) register, Instance loaded successfully.
2023-07-27 20:20:46 I/UnidbgFetchQsign: Bot(1810825454) initialize complete
2023-07-27 20:20:51 I/Bot.1810825454: Login successful
2023-07-27 20:20:51 I/Bot.1810825454: Saved account secrets to local cache for fast login.
2023-07-27 20:20:51 I/Bot.1810825454: Login successful.
2023-07-27 20:20:51 I/me.ericdeng.infra.QQPushServiceImpl: 正在等待主环境登录bot...
2023-07-27 20:20:52 V/Bot.1810825454: Event: BotOnlineEvent(bot=Bot(1810825454))
2023-07-27 20:20:52 I/Bot.1810825454: Bot login successful.
2023-07-27 20:20:52 V/Bot.1810825454: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Success@38d42ab7
2023-07-27 20:20:52 I/main: mirai-console started successfully.
2023-07-27 20:20:58 W/UnidbgFetchQsign: with CoroutineName(SendMessage)
java.lang.IllegalStateException: This mutex is not locked
        at fix-protocol-version-1.9.10.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.submit(UnidbgFetchQsign.kt:197)
        at fix-protocol-version-1.9.10.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$submit(UnidbgFetchQsign.kt:12)
        at fix-protocol-version-1.9.10.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$callback$1.invokeSuspend(UnidbgFetchQsign.kt:221)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by fuqiuluo** [comment]
并发太快了，刚刚准备超时解锁实例，实例就被解锁了

**Comment by EricDeng1001** [comment]
哈？但是我就只是正常启动而已呀？甚至我自己的插件都还没开始工作。这个准备修复么。作为程序员看这个报错难受

**Comment by EricDeng1001** [comment]
而且这个报错是在登陆成功之后一秒左右

**Comment by xiaomoL444** [comment]
嘿，我遇到了和你一样的问题，请问你解决了吗？我fix-protocol-version中发现你的issue没有后文了，想来问一下，谢了！

**Comment by xiaomoL444** [comment]
> 不好意思，没有仔细看日志。不是这个包的错误，我已经向原错误包提了issue

嘿，我遇到了和你一样的问题，请问你解决了吗？我fix-protocol-version中发现你的issue没有后文了，想来问一下，谢了！
