### ISSUE TITLE
go-cqhttp报错：获取sso sign时出现错误: Post "http://192.168.192.100:9081/sign": EOF server: http://192.168.192.100:9081/ 

### ISSUE THREAD

**Issue by icerxkx** [fuqiuluo/unidbg-fetch-qsign#18]
go-cqhttp最新版，Docker Image is up to date for xzhouqd/qsign:8.9.63
protocol为5，ipad协议，填写了android_id
错误如下：
`[FEKit_]info: device_info.h:629 create xwid step2 complete ret is 71

[FEKit_]info: device_token.h:89 create new xwId complete

[FEKit_]error: o3_channel_encrypt.h:275 gen new channel

FEBound.transform(8E9EC5D4690FD339E3D8975C1D76EB46A84C216859C1FB044E492D52DA854259) => D99C3C921A9ACE506CC4F050147F5AFB74F2B01D3A73AA9721F68E5E75A5FD9C

[FEKit_]error: o3_channel_encrypt.h:491 est check: 02fba67e641d9dc75cb000e95e3cabe5950883f9001b40eb3025711c8dd777c866fd1243f95665ac2e9825210d74fc46

[FEKit_]error: ChannelManager.cpp:72 o3cm@S: GetSecConf, trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey
uin = null, id = 0, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey, data = 0A0A476574536563436F6E661221027E8DBD85943EC065F586D73D273936CFF7BDF9757F8143AB19862C81A4F097AE22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652A494F368EDE638872FB4FB8767E7F862057C303C3EE03A23C5E4E78C735E3CBD17FDD847799064A0F1961F5CE0D59322822CE235C56F70A7DF6D038E32923745293CA8DEF3AE7DD434BAC322084A708CCDE67D8BD2C07D5D4A789768B3B37B76C4F87C3295D5955ACD58B71643A3002FBA67E641D9DC75CB000E95E3CABE5950883F9001B40EB3025711C8DD777C866FD1243F95665AC2E9825210D74FC46)

[FEKit_]error: device_token.h:151 uin empty!(0)
Receive (trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey) Data => size = 158 data: 0A9901B3E6DAD888649AC2006005F7A44FEF2F973BB73B3823FB9E12CD81EA90989589FA01B218F236871FDB683C380397A7C8E78E7A386F8E0D31E2A3D51716265F5E347687020C85AAD2ACBE414B6CA70FED2CCBB30C2CAE092A0DE606AD784ADCA2FFAEBE1A84F413229BFB602DF3948A296646F743A54D2B4E473E6A448B848C66EC383C3A5FF387C523EC01009FF26866817D5ECD55F1A60E3B1000

[FEKit_]info: ChannelManager.cpp:97 origin cmd:GetSecConf ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey

[FEKit_]error: ChannelManager.cpp:100 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey bcmd:GetSecConf

[FEKit_]info: task_handle.h:74 TaskSystem not allow
Jun 27, 2023 5:14:21 PM com.github.unidbg.linux.AndroidSyscallHandler getPipePair
INFO: Return default pipe pair.
Jun 27, 2023 5:14:21 PM com.github.unidbg.linux.ARM64SyscallHandler fork
INFO: fork
uin = null, id = -1, sendPacket(cmd = trpc.o3.report.Report.SsoReport, data = 0A0B3030653030303735363138128C010A1C56315F414E445F53515F382E392E36335F343138385F4844424D5F540A09362E3130302E3234380A2033356266323065326133653235626637313534373964366162373662313436640A243032326565666561623566393237353037333337303839663130303031353731373631390A0A656E765F6465746563740A04323030310A01200A01200A0120)
uin = null, id = -1, sendPacket(cmd = trpc.o3.report.Report.SsoReport, data = 0A0B3030653030303735363138128C010A1C56315F414E445F53515F382E392E36335F343138385F4844424D5F540A09362E3130302E3234380A2033356266323065326133653235626637313534373964366162373662313436640A243032326565666561623566393237353037333337303839663130303031353731373631390A0A656E765F6465746563740A04323030330A01200A01200A0120)

[FEKit_]info: task_handle.h:74 TaskSystem not allow
Exception in thread "DefaultDispatcher-worker-2" java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
        at io.ktor.network.sockets.CIOReaderKt$readFrom$2.invoke(CIOReader.kt:134)
        at io.ktor.network.sockets.CIOReaderKt$readFrom$2.invoke(CIOReader.kt:133)
        at io.ktor.utils.io.ByteBufferChannel.writeAvailable(ByteBufferChannel.kt:1466)
        at io.ktor.utils.io.ByteBufferChannel.write$suspendImpl(ByteBufferChannel.kt:1496)
        at io.ktor.utils.io.ByteBufferChannel.write(ByteBufferChannel.kt)
        at io.ktor.utils.io.ByteWriteChannel$DefaultImpls.write$default(ByteWriteChannel.kt:88)
        at io.ktor.network.sockets.CIOReaderKt.readFrom(CIOReader.kt:133)
        at io.ktor.network.sockets.CIOReaderKt.access$readFrom(CIOReader.kt:1)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1.invokeSuspend(CIOReader.kt:109)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:189)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKey(SelectorManagerSupport.kt:84)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKeys(SelectorManagerSupport.kt:65)
        at io.ktor.network.selector.ActorSelectorManager.process(ActorSelectorManager.kt:70)
        at io.ktor.network.selector.ActorSelectorManager.access$process(ActorSelectorManager.kt:18)
        at io.ktor.network.selector.ActorSelectorManager$process$1.invokeSuspend(ActorSelectorManager.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@38091dd, Dispatchers.IO]`

**Comment by icerxkx** [comment]
是docker的问题，用源代码部署没问题
