### ISSUE TITLE
1.1.7 `java.lang.IllegalStateException: This mutex is not locked`

### ISSUE THREAD

**Issue by Coloryr** [fuqiuluo/unidbg-fetch-qsign#190]
```
[FEKit_]info: task_handle.h:74 TaskSystem not allow
clock_gettime clk_id=1, tp=RW@0x410fee48, offset=18768000796, tv_sec=18, tv_nsec=768000796
clock_gettime clk_id=0, tp=RW@0x410fee48, offset=1691337526322000000, tv_sec=1691337526, tv_nsec=322000000
clock_gettime clk_id=0, tp=RW@0x410fee30, offset=1691337526353000000, tv_sec=1691337526, tv_nsec=353000000
Aug 06, 2023 3:58:46 PM com.github.unidbg.linux.AndroidSyscallHandler getPipePair
INFO: Return default pipe pair.
Aug 06, 2023 3:58:46 PM com.github.unidbg.linux.ARM64SyscallHandler fork
INFO: fork
clock_gettime clk_id=1, tp=RW@0x4147bae8, offset=19707757648, tv_sec=19, tv_nsec=707757648
clock_gettime clk_id=0, tp=RW@0x4147bae8, offset=1691337527262000000, tv_sec=1691337527, tv_nsec=262000000
clock_gettime clk_id=0, tp=RW@0x4147bad0, offset=1691337527273000000, tv_sec=1691337527, tv_nsec=273000000
Aug 06, 2023 3:58:47 PM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /proc/self/cmdline
Aug 06, 2023 3:58:47 PM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/lib/arm64
[FEKit_]info: task_handle.h:74 TaskSystem not allow
[15:58:51.406][WARN]with CoroutineName(SendMessage) java.lang.IllegalStateException: This mutex is not locked
        at xyz.cssxsh.mirai.tool.UnidbgFetchQsign.submit(UnidbgFetchQsign.kt:194) ~[?:?]
        at xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$submit(UnidbgFetchQsign.kt:12) ~[?:?]
        at xyz.cssxsh.mirai.tool.UnidbgFetchQsign$callback$1.invokeSuspend(UnidbgFetchQsign.kt:214) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[ColorMirai-4.1.11-all.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[ColorMirai-4.1.11-all.jar:?]
```

Ubuntu22.04 用的 ANDROID_PAD 8.9.63

**Comment by fuqiuluo** [comment]
不用管这个

**Comment by CVKNO80098** [comment]
虽然但是我的卡在这了，虽然知道可能不是这个步骤的，但是还是来问一下，有啥解决这种卡住的方法吗，看服务器CPU才1.多，内存也才不到20%
