### ISSUE TITLE
1.1.7无法正常启动

### ISSUE THREAD

**Issue by Guyao146** [fuqiuluo/unidbg-fetch-qsign#193]
windows server系统 Jdk 11
日志如下
C:\Users\Administrator\Desktop\bot\server\bin>start.bat
Exception in thread "main" java.lang.IllegalArgumentException: Lack of basePath.
        at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:29)
        at MainKt.main(Main.kt:32)

**Comment by rhwong** [comment]
逆天

**Comment by KewenCode** [comment]
同情况，早上正常启动，下午重启签名报错
Exception in thread "main" java.lang.IllegalStateException: The base path is invalid, perhaps it is not a directory or something is missing inside.
        at MainKt.main(Main.kt:42)

**Comment by zanjie1999** [comment]
目前的最新版也有这个问题，同样的方式可以启动1.0

**Comment by zanjie1999** [comment]
太草了，没做向下兼容，目前需要使用config.json启动，需要重新按说明配置，并且还没判断就直接读取配置，所以报错并且输出匪夷所思的错误
