### ISSUE TITLE
【8月12号】最新gocq dev登录时出现Code 45问题 #200

### ISSUE THREAD

**Issue by FuYon** [fuqiuluo/unidbg-fetch-qsign#201]
我的nonebot配置（使用你的一键包）：
```
HOST=127.0.0.1
PORT=19191
```

我的gocq配置：
```
  sign-server: 'http://127.0.0.1:29291'
  sign-server-bearer: '-'
  is-below-110: false
  key: '213467811'
  auto-register: false
  auto-refresh-token: false
  refresh-interval: 40
  - ws-reverse:
      universal: ws://127.0.0.1:19191/onebot/v11/ws
      api: ws://your_websocket_api.server
      event: ws://your_websocket_event.server
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
gocq输出日志
```
[2023-08-12 00:41:46] [INFO]: 当前版本:ce119b7
[2023-08-12 00:41:46] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备.
[2023-08-12 00:41:47] [INFO]: 已生成设备信息并保存到 device.json 文件.
[2023-08-12 00:41:47] [INFO]: 使用服务器 http://127.0.0.1:29291 进行数据包签名
[2023-08-12 00:41:52] [INFO]: 连接至签名服务器: http://127.0.0.1:29291
[2023-08-12 00:41:55] [INFO]: 注册QQ实例 1691914478 成功: The QQ has already loaded an instance, so this time it is deleting the existing instance and creating a new one.
[2023-08-12 00:41:55] [INFO]: 每 40 分钟将刷新一次签名 token
[2023-08-12 00:41:55] [WARNING]: 自动注册实例已关闭，若未配置 sign-server 端自动注册实例则实例丢失时需要重启 go-cqhttp
以正常签名
[2023-08-12 00:41:55] [WARNING]: 自动刷新 token 已关闭，token 过期后获取签名时将不会立即尝试刷新获取新 token
[2023-08-12 00:41:55] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-08-12 00:42:00] [INFO]: 开始尝试登录并同步消息...
[2023-08-12 00:42:00] [INFO]: 使用协议: Android Pad 8.9.63.11390
[2023-08-12 00:42:00] [INFO]: 正在检查协议更新...
[2023-08-12 00:42:07] [INFO]: Protocol -> connect to server: 220.194.118.230:8080
[2023-08-12 00:42:09] [WARNING]: 登录失败: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。 Code: 45
[2023-08-12 00:42:09] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试
[2023-08-12 00:42:09] [INFO]: 按 Enter 继续....
[2023-08-12 00:42:09] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005
[2023-08-12 00:42:24] [WARNING]: callback error: Packet timed out
panic: runtime error: slice bounds out of range [-10:]

goroutine 48 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signSubmit({0xc0003f2010, 0xa}, {0xc0000cc628, 0x33}, 0x1?, {0x0, 0x0, 0x0?}, {0x146cf63, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:316 +0x5c5
github.com/Mrs4s/go-cqhttp/cmd/gocq.signCallback({0xc0003f2010, 0xa}, {0xc00040a140?, 0x3, 0x0?}, {0x146cf63, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:337 +0xb1
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.signRequset
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:365 +0xcb0

E:\111Bot\gocq>
```

我的device.json（默认生成）
```
{"display":"MIRAI.230141.001","product":"mirai","device":"mirai","board":"mirai","model":"mirai","finger_print":"mamoe/mirai/mirai:10/MIRAI.200122.001/2669946:user/release-keys","boot_id":"051bbacc-3dc4-edfe-f725-a4aec4436b76","proc_version":"Linux version 3.0.31-uTWPrkzM (android-build@xxx.xxx.xxx.xxx.com)","protocol":6,"imei":"101455853688020","brand":"mamoe","bootloader":"unknown","base_band":"","version":{"incremental":"5891938","release":"10","codename":"REL","sdk":29},"sim_info":"T-Mobile","os_type":"android","mac_address":"00:50:56:C0:00:08","ip_address":[10,0,1,3],"wifi_bssid":"00:50:56:C0:00:08","wifi_ssid":"\u003cunknown ssid\u003e","imsi_md5":"06b9625c154308550a6d944224fb0006","android_id":"5956b4b18dd04de2","apn":"wifi","vendor_name":"MIUI","vendor_os_name":"mirai"}
```

**Comment by FuYon** [comment]
应该是因为我使用了不受支持的最新的qsign1.17b所导致，请问目前最高支持到多少？

**Comment by mhcms** [comment]
gocq默认协议是 8.9.63.11390，而你部署的qsign是8.9.73的

**Comment by xiwangly2** [comment]
> gocq默认协议是 8.9.63.11390，而你部署的qsign是8.9.73的

可以在 go-cqhttp 的`data/versions`目录下使用 [num].json 自定义使用的协议，例如6.json写入
```json
{
    "apk_id": "com.tencent.mobileqq",
    "app_id": 537169425,
    "sub_app_id": 537169425,
    "app_key": "0S200MNJT807V3GE",
    "sort_version_name": "8.9.70.11635",
    "build_time": 1689572864,
    "apk_sign": "c67b3780e3a04a0de773115beafebb42",
    "sdk_version": "6.0.0.2551",
    "sso_version": 20,
    "misc_bitmap": 150470524,
    "main_sig_map": 34869472,
    "sub_sig_map": 66560,
    "dump_time": 1689651775,
    "qua": "V1_AND_SQ_8.9.70_4292_HDBM_T",
    "protocol_type": 6
}
```

然后重新启动 go-cqhttp
```bash
[2023-08-12 10:15:51] [INFO]: 当前版本:(devel) 
[2023-08-12 10:15:51] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-08-12 10:15:52] [INFO]: 使用服务器 http://192.168.85.11 进行数据包签名 
[2023-08-12 10:15:58] [INFO]: 连接至签名服务器: http://192.168.85.11
[2023-08-12 10:16:07] [INFO]: 注册QQ实例 114514 成功: The QQ has already loaded an instance, so this time it is deleting the existing instance and creating a new one. 
[2023-08-12 10:16:07] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-08-12 10:16:07] [INFO]: 每 30 分钟将刷新一次签名 token 
[2023-08-12 10:16:12] [INFO]: 开始尝试登录并同步消息... 
[2023-08-12 10:16:12] [INFO]: 使用协议: Android Pad 8.9.63.11390 
[2023-08-12 10:16:12] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.70.11635. 
[2023-08-12 10:16:17] [INFO]: Protocol -> connect to server: 114.221.144.150:8080 
[2023-08-12 10:16:20] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail. 
[2023-08-12 10:16:22] [INFO]: 正在检查协议更新... 
[2023-08-12 10:16:22] [INFO]: submit sign: uin=114514, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=0, buffer=[10 153 1 180 20 33 25 73 91 49 87 136 12 136 201 227 191 99 236 133 83 250 214 64 142 241 223 251 19 66 126 153 148 196 184 102 47 68 226 7 226 17 3 135 210 146 106 143 212 245 132 58 152 233 56 94 3 252 170 160 83 11 167 5]...
[2023-08-12 10:16:22] [INFO]: 检测到协议更新: 8.9.70.11635 -> 8.9.63.11390 
[2023-08-12 10:16:22] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动
[2023-08-12 10:16:22] [INFO]: 登录成功 欢迎使用: ⁭
[2023-08-12 10:16:23] [INFO]: 开始加载好友列表...
[2023-08-12 10:16:23] [INFO]: 共加载 9 个好友. 
[2023-08-12 10:16:23] [INFO]: 开始加载群列表...
[2023-08-12 10:16:23] [INFO]: 共加载 7 个群. 
[2023-08-12 10:16:23] [INFO]: 资源初始化完成, 开始处理信息. 
[2023-08-12 10:16:23] [INFO]: アトリは、高性能ですから!
[2023-08-12 10:16:23] [INFO]: 正在检查更新.
[2023-08-12 10:16:23] [WARNING]: 检查更新失败: 使用的 Actions 测试版或自编译版本.
[2023-08-12 10:16:23] [INFO]: 开始诊断网络情况
[2023-08-12 10:16:23] [INFO]: CQ WebSocket 服务器已启动: [::]:6700
[2023-08-12 10:16:26] [INFO]: 网络诊断完成. 未发现问题 
[2023-08-12 10:16:29] [INFO]: submit sign: uin=114514, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=1, buffer=[10 148 1 196 175 149 112 7 247 239 187 129 27 255 240 167 87 67 92 200 170 50 94 7 171 172 56 218 25 27 71 139 68 55 38 31 141 243 193 178 4 249 63 45 237 26 158 233 224 193 117 207 20 216 103 131 246 92 46 11 35 244 2 47]...

```
应该就行了
