### ISSUE TITLE
为什么签名登录后会报错，是因为没有配置吗还是协议不同

### ISSUE THREAD

**Issue by Xixi14** [fuqiuluo/unidbg-fetch-qsign#210]
### Discussed in https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **Xixi14** August 14, 2023</sup>
> 2023-08-14 09:31:42 I/QSignService: 已注册加密算法提供服务
2023-08-14 09:31:42 I/plugin: Successfully loaded plugin QSign v1.0.7
2023-08-14 09:31:42 I/plugin: Successfully loaded plugin PluginVoodoo v1.6.1
2023-08-14 09:31:42 I/plugin: Successfully loaded plugin mirai-device-generator v1.2.0
2023-08-14 09:31:42 I/plugin: Successfully loaded plugin MuteGames v0.0.4
2023-08-14 09:31:42 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2023-08-14 09:31:46 I/LuckPerms: Loading configuration...
2023-08-14 09:31:47 I/LuckPerms: Loading storage provider... [H2]
2023-08-14 09:31:52 I/LuckPerms: Loading internal permission managers...
2023-08-14 09:31:52 I/LuckPerms: Performing initial data load...
2023-08-14 09:31:53 I/LuckPerms: Registering internal users....
2023-08-14 09:31:53 I/LuckPerms: Successfully enabled. (took 8769ms)
2023-08-14 09:31:53 I/plugin: Successfully loaded plugin LuckPerms v2.14.0-dev-7+null
2023-08-14 09:31:54 I/plugin: Successfully loaded plugin J Picture Archiving v0.1.1
2023-08-14 09:31:54 I/QRLogin: Loading QRLogin v0.1.9
2023-08-14 09:31:54 W/QRLogin: 本插件仅在 2.15.0 或以上工作，且在正式版或先行发布版(RC)中可能无法使用
2023-08-14 09:31:54 I/plugin: Successfully loaded plugin QRLogin v0.1.9
2023-08-14 09:31:54 I/fix-protocol-version: 协议版本检查更新...
2023-08-14 09:31:54 I/fix-protocol-version: 注册服务...
2023-08-14 09:31:54 I/plugin: Successfully loaded plugin fix-protocol-version v1.8.4
2023-08-14 09:31:54 I/plugin: Successfully loaded plugin J Nudge Reply v1.4.0
2023-08-14 09:32:01 I/mirai-hibernate-plugin: Driver: org.h2.Driver Version 2.1
2023-08-14 09:32:01 I/mirai-hibernate-plugin: Driver: com.mysql.cj.jdbc.Driver Version 8.0
2023-08-14 09:32:01 I/mirai-hibernate-plugin: Driver: org.mariadb.jdbc.Driver Version 3.1
2023-08-14 09:32:01 I/mirai-hibernate-plugin: Driver: org.postgresql.Driver Version 42.5
2023-08-14 09:32:01 I/mirai-hibernate-plugin: Driver: org.sqlite.JDBC Version 3.41
2023-08-14 09:32:02 I/mirai-hibernate-plugin: Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver Version 11.2
2023-08-14 09:32:02 I/plugin: Successfully loaded plugin mirai-hibernate-plugin v2.7.1
2023-08-14 09:32:03 I/plugin: Successfully loaded plugin HuYanSession v2.3.2
2023-08-14 09:32:03 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-08-14 09:32:03 I/main: Loaded PermissionService from plugin LuckPerms
2023-08-14 09:32:05 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-08-14 09:32:07 I/mirai-administrator: 机器人所有者 xx
2023-08-14 09:32:07 I/mirai-administrator: 发送上线通知请使用 /perm add g群号 xyz.cssxsh.mirai.plugin.mirai-administrator:online.include 赋予权限
2023-08-14 09:32:07 I/mirai-administrator: 发送留言评论请使用 /perm add u1234 xyz.cssxsh.mirai.plugin.mirai-administrator:comment.include 赋予权限
2023-08-14 09:32:07 I/mirai-administrator: 定时消息部分功能更新了，请查看最新版文档
2023-08-14 09:32:07 I/mirai-administrator: censor_regex 配置项废除, 改为加载 censor 文件夹中的 txt 文件（不需要重启，会监听文件修改）
2023-08-14 09:32:07 I/mirai-administrator: ComparableService Registered [10]:
BackupService: default-backup
BlackListService: default-blacklist
BotOnlineAction: online
ContentCensor: default-censor
FriendApprover: default-approver
GroupApprover: default-approver
MemberApprover: default-approver
MessageSourceHandler: hibernate-recorder
TimerService: cleaner, curfew-timer, message-timer, status

2023-08-14 09:32:10 I/RiskDetector: Plugin loaded
2023-08-14 09:32:10 I/PluginVoodoo: VoodooPlugin loaded
2023-08-14 09:32:13 I/MuteGames: 决斗已加载7个击中部位，共加载概率为411
2023-08-14 09:32:14 I/MuteGames: 禁言游戏已加载
2023-08-14 09:32:14 I/J Picture Archiving: Plugin loaded
2023-08-14 09:32:14 I/QRLogin: 正在启用插件 QRLogin v0.1.9
2023-08-14 09:32:14 I/QRLogin: Mirai 版本: 2.15.0
2023-08-14 09:32:15 I/QRLogin: 正在进行自动登录...
2023-08-14 09:32:15 I/QRLogin: Auto-login 1450234719, protocol: ANDROID_WATCH, heartbeatStrategy: STAT_HB
2023-08-14 09:32:15 W/QRLoginSolver: 当前没有桌面环境，将不使用窗口式扫码登录监听器。
2023-08-14 09:32:15 I/QRLoginSolver: 登录解决器更换为 QRLoginSolver
2023-08-14 09:32:16 W/EncryptService.alert: Encrypt service was loaded: top.mrxiaom.qsign.QSignService$Factory@166a5659
2023-08-14 09:32:16 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-08-14 09:32:16 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-08-14 09:32:16 W/EncryptService.alert: Service details:
2023-08-14 09:32:16 W/EncryptService.alert:   `- Jvm Class: class top.mrxiaom.qsign.QSignService$Factory
2023-08-14 09:32:16 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{qsign-1.0.7.mirai2.jar}
2023-08-14 09:32:16 W/EncryptService.alert:   `- Source: file:/workspace/plugins/qsign-1.0.7.mirai2.jar
2023-08-14 09:32:16 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/workspace/plugins/qsign-1.0.7.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{qsign-1.0.7.mirai2.jar}
 <no principals>
 java.security.Permissions@4feaa4b8 (
 ("java.io.FilePermission" "/workspace/plugins/qsign-1.0.7.mirai2.jar" "read")
)

2023-08-14 09:32:16 W/Bot.xx: top.mrxiaom.qsign.QSignService$Factory@166a5659 is not yet supported EncryptService with bot Bot(xx)
java.lang.UnsupportedOperationException: QSignService only supports ANDROID_PHONE, ANDROID_PAD.
	at qsign-1.0.7.mirai2.jar//top.mrxiaom.qsign.QSignService$Factory.createForBot(QSignService.kt:156)
	at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
	at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.access$getScope(SelectorNetworkHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection$suspendImpl(SelectorNetworkHandler.kt:130)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection(SelectorNetworkHandler.kt)
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:145)
	at mirai-console-dev-qrlogin-0.1.9.mirai2.jar//top.mrxiaom.qrlogin.QRAutoLoginConfig$runAutoLogin$1.invokeSuspend(QRAutoLoginConfig.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at mirai-console-dev-qrlogin-0.1.9.mirai2.jar//top.mrxiaom.qrlogin.QRAutoLoginConfig.runAutoLogin(QRAutoLoginConfig.kt:88)
	at mirai-console-dev-qrlogin-0.1.9.mirai2.jar//top.mrxiaom.qrlogin.QRLogin.onEnable(QRLogin.kt:52)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:237)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:308)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:39)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:359)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
</div>

**Comment by Dream-Rainy** [comment]
报错中提到不支持ANDROID_WATCH协议，建议删除qrlogin插件并修改autologin配置文件中的协议为ANDROID_PHONE或者ANDROID_PAD，然后重试

**Comment by rhwong** [comment]
Successfully loaded plugin QSign v1.0.7

**Comment by MrXiaoM** [comment]
插件的 README 让你可以无脑使用 ANDROID_PHONE 或者 ANDROID_PAD 协议登录，结果你用了 ANDROID_WATCH 协议登录。不仅如此，你还把 下游 fork 的报错发到了上游仓库
