### ISSUE TITLE
Bad magic number for file

### ISSUE THREAD

**Issue by Gimhoy** [fuqiuluo/unidbg-fetch-qsign#22]
请问这个怎么解决呀？

09:24:09.943 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
09:24:09.945 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
09:24:09.945 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
09:24:09.945 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libdynarmic.so
09:24:09.945 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/var/www/qsign/lib/unidbg-fix.jar!/natives/linux_64/libdynarmic.so
09:24:09.945 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/var/www/qsign/lib/unidbg-fix.jar!/natives/linux_64/libdynarmic.so
09:24:09.958 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/var/www/qsign/lib/unidbg-fix.jar!/natives/linux_64/libdynarmic.so' to '/tmp/nativelib-loader_2426129071031544655/libdynarmic.so'
09:24:10.237 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
Jun 28, 2023 9:24:11 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: stdin
Jun 28, 2023 9:24:11 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: stdout
Jun 28, 2023 9:24:11 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: stderr
09:24:11.176 [WorkerPool: MainKt$$Lambda$13/0x0000000800c18230@17f6480] ERROR moe.fuqiuluo.unidbg.QSecVM - Failed to init QSign: net.fornwall.jelf.ElfException: Bad magic number for file
net.fornwall.jelf.ElfException: Bad magic number for file
        at net.fornwall.jelf.ElfFile.<init>(ElfFile.java:271)
        at net.fornwall.jelf.ElfFile.fromBuffer(ElfFile.java:259)
        at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:316)
        at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:174)
        at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:62)
        at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
        at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:315)
        at moe.fuqiuluo.unidbg.vm.AndroidVM.loadLibrary(AndroidVM.kt:38)
        at moe.fuqiuluo.unidbg.QSecVM.init(QSecVm.kt:65)
        at MainKt$main$2$1$1.invoke(Main.kt:64)
        at MainKt$main$2$1$1.invoke(Main.kt:63)
        at moe.fuqiuluo.unidbg.QSecVMWorker.work(QSecVm.kt:26)
        at MainKt.main$lambda$2(Main.kt:63)
        at moe.fuqiuluo.unidbg.pool.FixedWorkPool.run(FixedWorkPool.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by fuqiuluo** [comment]
你是不是导入Tim的so文件了？

**Comment by fuqiuluo** [comment]
so文件对应的QQ版本发一下

**Comment by Gimhoy** [comment]
8.9.63啊，就是库里的那个so

**Comment by fuqiuluo** [comment]
so文件丢包下载错了吧，残缺了，导致加载失败

**Comment by Gimhoy** [comment]
重新下载好了，谢谢大佬~
