### ISSUE TITLE
sh命令台上启动成功，但是查询发现运行失败

### ISSUE THREAD

**Issue by CVKNO80098** [fuqiuluo/unidbg-fetch-qsign#220]
出现了

```
The base path is invalid, perhaps it is not a directory or something is missing inside.
        at MainKt.main(Main.kt:42)
```
查询log发现
```
Aug 20 19:12:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Failed with result 'exit-code'.
Aug 20 19:13:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Scheduled restart job, restart counter is at 13.
Aug 20 19:13:51 RainYun-3QGRNIJ9 systemd[1]: Stopped unidbg-fetch-qsign.
Aug 20 19:13:51 RainYun-3QGRNIJ9 systemd[1]: Started unidbg-fetch-qsign.
Aug 20 19:13:51 RainYun-3QGRNIJ9 bash[7997]: Exception in thread "main" java.lang.IllegalStateException: The base path is invalid, perhaps it is not a directory or something is m>Aug 20 19:13:51 RainYun-3QGRNIJ9 bash[7997]:         at MainKt.main(Main.kt:42)
Aug 20 19:13:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 19:13:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Failed with result 'exit-code'.
Aug 20 19:14:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Scheduled restart job, restart counter is at 14.
Aug 20 19:14:51 RainYun-3QGRNIJ9 systemd[1]: Stopped unidbg-fetch-qsign.
Aug 20 19:14:51 RainYun-3QGRNIJ9 systemd[1]: Started unidbg-fetch-qsign.
Aug 20 19:14:51 RainYun-3QGRNIJ9 bash[8047]: Exception in thread "main" java.lang.IllegalStateException: The base path is invalid, perhaps it is not a directory or something is m>Aug 20 19:14:51 RainYun-3QGRNIJ9 bash[8047]:         at MainKt.main(Main.kt:42)
Aug 20 19:14:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 19:14:51 RainYun-3QGRNIJ9 systemd[1]: qsign.service: Failed with result 'exit-code'.
```
求解决

**Comment by callng** [comment]
The base path is invalid, perhaps it is not a directory or something is m
