### ISSUE TITLE
登录的版本8.9.73，fix-protocol-version版本V1.1.9 2小时后必风控

### ISSUE THREAD

**Issue by HOursH** [fuqiuluo/unidbg-fetch-qsign#248]
一个月之前就试过8.9.73了，当时用的版本是：[1.1.7b2](https://github.com/fuqiuluo/unidbg-fetch-qsign/releases/tag/1.1.7b2)
当时也是登录成功，但是2小时后必冻结，当时退回到8.9.63就没事了，2小时前又试了一下，因为8.9.63当时报错了，就换成了8.9.73，还是2小时后必冻结。
ubuntu22.04，fix-protocol-version版本是1.1.9，fix-protocol-version使用的java版本是java8
fix-protocol-version使用的版本是[v1.11.0](https://github.com/cssxsh/fix-protocol-version/releases/tag/v1.11.0)
我2小时前就在discussions提交过logs：https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/247

2023-09-13 18:41:36 V/Bot.xxx: Event: BotOfflineEvent.MsfOffline(bot=Bot(xxx), cause=MsfOfflineToken(uin=xxx, seq=4157396881, const=0), reconnect=true)
2023-09-13 18:41:36 W/Bot.xxx: Server notifies offline. (dropped by StatSvc.ReqMSFOffline)
2023-09-13 18:41:36 I/UnidbgFetchQsign: Bot(xxx) initialize by http://127.0.0.1:8080
2023-09-13 18:41:36 I/UnidbgFetchQsign: Bot(xxx) initialize complete
2023-09-13 18:41:50 I/UnidbgFetchQsign: Bot(xxx) destroy, Instance destroyed successfully.
2023-09-13 18:41:50 I/Bot.3327412318: Bot cancelled: Bot closed
fix-protocol-version封掉时候的logs：
Read 4 bytes from '/dev/urandom'
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Read 4 bytes from '/dev/urandom'
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Read 4 bytes from '/dev/urandom'
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Accept static com/tencent/mobileqq/dt/model/FEBound->transform(I[B)[B
JNIEnv->GetStaticMethodID(com/tencent/mobileqq/dt/model/FEBound.transform(I[B)[B) => 0x5291e1bd was called from RX@0x403a9bc0[libfekit.so]0x3a9bc0
JNIEnv->NewByteArray(57) was called from RX@0x401d1244[libfekit.so]0x1d1244
JNIEnv->SetByteArrayRegion([B@23c51e3c, 0, 57, RW@0x41145480) was called from RX@0x401d1280[libfekit.so]0x1d1280
JNIEnv->CallStaticObjectMethodV(class com/tencent/mobileqq/dt/model/FEBound, transform(0x2, [B@23c51e3c) => [B@65c8205a) was called from RX@0x401d1c94[libfekit.so]0x1d1c94
JNIEnv->GetArrayLength([B@65c8205a => 57) was called from RX@0x401d12b0[libfekit.so]0x1d12b0
File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Read 4 bytes from '/dev/urandom'
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
JNIEnv->NewByteArray(64) was called from RX@0x400b7440[libfekit.so]0xb7440
JNIEnv->SetByteArrayRegion([B@7e70f7a6, 0, 64, RW@0x40c1e550) was called from RX@0x400b755c[libfekit.so]0xb755c
JNIEnv->ReleaseStringUTFChars("wtlogin.login") was called from RX@0x403aaa84[libfekit.so]0x3aaa84
JNIEnv->SetObjectField(com.tencent.mobileqq.sign.QQSecuritySign$SignResult@64de50f3, sign [B => [B@7e70f7a6) was called from RX@0x40162614[libfekit.so]0x162614
JNIEnv->ReleaseStringUTFChars("V1_AND_SQ_8.9.73_4416_YYB_D") was called from RX@0x40153da8[libfekit.so]0x153da8
JNIEnv->ReleaseStringUTFChars("wtlogin.login") was called from RX@0x40153dc0[libfekit.so]0x153dc0
JNIEnv->ReleaseStringUTFChars("3327412318") was called from RX@0x40153dec[libfekit.so]0x153dec

**Comment by HOursH** [comment]
登录的是ANDROID_PAD

**Comment by HOursH** [comment]
现在用8.9.63就报45,现在怎么办？：
2023-09-13 19:51:37 I/KFCFactory: ANDROID_PAD(8.9.63) EncryptService by fuqiuluo/unidbg-fetch-qsign from file:///bot/KFCFactory.json
2023-09-13 19:51:37 I/KFCFactory: unidbg-fetch-qsign by http://127.0.0.1:8080 about 
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.9",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
            "version": "8.9.63",
            "code": "4194",
            "package_name": "com.tencent.mobileqq"
        }
    }
}
2023-09-13 19:51:38 I/UnidbgFetchQsign: Bot(xxx) initialize by http://127.0.0.1:8080
2023-09-13 19:51:41 E/MahKtorAdapter[http,ws]: Websocket handler failed
java.util.NoSuchElementException
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.context.session.manager.DefaultSessionManager.authSession(default.kt:50)
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.ws.router.BaseKt$wsRouter$1$invoke$$inlined$miraiWebsocket$3.invokeSuspend(utils.kt:60)
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.ws.router.BaseKt$wsRouter$1$invoke$$inlined$miraiWebsocket$3.invoke(utils.kt)
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.ws.router.BaseKt$wsRouter$1$invoke$$inlined$miraiWebsocket$3.invoke(utils.kt)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt.handleServerSession(Routing.kt:251)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt.proceedWebSocket(Routing.kt:237)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt.access$proceedWebSocket(Routing.kt:1)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocket$2.invokeSuspend(Routing.kt:201)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocket$2.invoke(Routing.kt)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocket$2.invoke(Routing.kt)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.invokeSuspend(Routing.kt:105)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.invoke(Routing.kt)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.invoke(Routing.kt)
        at mirai-api-http-2.9.1.mirai2.jar[shared]//io.ktor.server.websocket.WebSocketUpgrade$upgrade$2.invokeSuspend(WebSocketUpgrade.kt:99)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-09-13 19:51:49 I/UnidbgFetchQsign: Bot(xxx) register, Instance loaded successfully.
2023-09-13 19:51:49 I/UnidbgFetchQsign: Bot(xxx) initialize complete
Login failed: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
2023-09-13 19:51:54 E/console: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ 后重试。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com 下载最新版QQ后重试。, errorInfo=)]

2023-09-13 19:51:55 W/UnidbgFetchQsign: with CoroutineName(SendMessage)
java.lang.RuntimeException: Bot(3327412318) callback trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
      at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$callback$1.invokeSuspend(UnidbgFetchQsign.kt:236)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.util.concurrent.CancellationException: net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
      at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:157)
      at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
      at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:194)
      at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt$createChannelProxy$1.sendMessage(OutgoingPacket.kt:328)
      at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$callback$1.invokeSuspend(UnidbgFetchQsign.kt:229)
      ... 6 more
Caused by: net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
      at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
      ... 6 more
      Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
      at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
      at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
      ... 6 more
      Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后 重试。, errorInfo=)
              at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
              at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
              at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
              at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
              at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
              at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
              ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com 下载最新版QQ后重试。, errorInfo=)]

2023-09-13 19:51:56 I/UnidbgFetchQsign: Bot(xxx) destroy, Instance destroyed successfully.
2023-09-13 19:51:56 I/Bot.xxx: Bot cancelled: Bot closed
>

**Comment by Dream-Rainy** [comment]
qsign自带的是手机版qq的签名文件，你用平板协议会导致无法签名，所以就不会进行签名登陆了，成功签名后的日志应该为
```
2023-09-13 09:03:14 I/Bot.3558494075: Loaded account secrets from local cache.
2023-09-13 09:03:15 I/UnidbgFetchQsign: Bot() initialize by http://127.0.0.1:8090
2023-09-13 09:03:35 I/UnidbgFetchQsign: Bot() register, Instance loaded successfully.
2023-09-13 09:03:35 I/UnidbgFetchQsign: Bot() initialize complete
```
请自行修改配置文件添加平板签名文件或换用手机协议登陆

**Comment by HOursH** [comment]
> qsign自带的是手机版qq的签名文件，你用平板协议会导致无法签名，所以就不会进行签名登陆了，成功签名后的日志应该为
> 
> ```
> 2023-09-13 09:03:14 I/Bot.: Loaded account secrets from local cache.
> 2023-09-13 09:03:15 I/UnidbgFetchQsign: Bot() initialize by http://127.0.0.1:8090
> 2023-09-13 09:03:35 I/UnidbgFetchQsign: Bot() register, Instance loaded successfully.
> 2023-09-13 09:03:35 I/UnidbgFetchQsign: Bot() initialize complete
> ```
> 
> 请自行修改配置文件添加平板签名文件或换用手机协议登陆 ![QQ截图20230914104608](https://user-images.githubusercontent.com/88184993/267837460-0153c529-62c5-448f-9358-8fb8ae413095.png)

1,这是我当时使用8.9.73登录成功的logs：
 JvmPluginClassLoader{fix-protocol-version-1.11.0.mirai2.jar}
 <no principals>
 java.security.Permissions@4f737d8c (
 ("java.io.FilePermission" "/bot/plugins/fix-protocol-version-1.11.0.mirai2.jar" "read")
)


2023-09-13 16:16:12 I/KFCFactory: ANDROID_PAD(8.9.73) EncryptService by fuqiuluo/unidbg-fetch-qsign from file:///bot/KFCFactory.json
2023-09-13 16:16:12 I/KFCFactory: unidbg-fetch-qsign by http://127.0.0.1:8080 about 
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.9",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.73_4416_YYB_D",
            "version": "8.9.73",
            "code": "4332",
            "package_name": "com.tencent.mobileqq"
        }
    }
}
2023-09-13 16:16:13 I/UnidbgFetchQsign: Bot(xxx) initialize by http://127.0.0.1:8080
2023-09-13 16:16:25 I/UnidbgFetchQsign: Bot(xxx) register, Instance loaded successfully.
2023-09-13 16:16:25 I/UnidbgFetchQsign: Bot(xxx) initialize complete
2023-09-13 16:17:30 I/Bot.xxx: Login successful
2023-09-13 16:17:30 I/Bot.xxx: Saved account secrets to local cache for fast login.
2023-09-13 16:17:30 I/Bot.xxx: Login successful.
2023-09-13 16:17:40 V/Bot.xxx: Event: BotOnlineEvent(bot=Bot(xxx))
2023-09-13 16:17:40 I/Bot.xxx: Bot login successful.

2,难道[8.9.63](https://github.com/fuqiuluo/unidbg-fetch-qsign/tree/master/txlib/8.9.63)支持pad登录，[8.9.73](https://github.com/fuqiuluo/unidbg-fetch-qsign/tree/master/txlib/8.9.73)就不支持pad登录了？
3，我现在如果使用https://github.com/MrXiaoM/qsign/ 直接登录8.9.73，并且选择PAD，还会有冻结的风险吗？
2023-09-14 12:20:44 I/QSign: Loading QSign v1.1.0-beta (unidbg-fetch-qsign v1.1.9)
2023-09-14 12:20:44 I/QSign: 正在 Mirai 2.15.0 上运行
2023-09-14 12:20:44 I/QSign: 签名服务目录: /bot/txlib/8.9.73
2023-09-14 12:20:44 I/QSign: FEBound sum = 7680
2023-09-14 12:20:44 I/QSign: 已成功读取签名服务配置
2023-09-14 12:20:44 I/QSign:   签名协议包名: com.tencent.mobileqq
2023-09-14 12:20:44 I/QSign:   签名服务版本: 8.9.73
2023-09-14 12:20:44 I/QSign:   签名服务QUA: V1_AND_SQ_8.9.73_4416_YYB_D
2023-09-14 12:20:44 I/QSign: =============================================
2023-09-14 12:20:44 I/QSign: 已加载 ANDROID_PHONE 协议变更: 8.9.73.11945 (2023年07月26日 19:31:31)
2023-09-14 12:20:44 I/QSign: 已加载 ANDROID_PAD 协议变更: 8.9.73.11945 (2023年07月26日 19:31:31)
2023-09-14 12:20:44 I/QSign: 支持签名服务的协议: ANDROID_PHONE, ANDROID_PAD
2023-09-14 12:20:44 I/QSignService: 已注册加密算法提供服务
2023-09-14 12:20:44 I/plugin: Successfully loaded plugin QSign v1.1.0-beta

**Comment by Dream-Rainy** [comment]
下游项目[qsign](https://github.com/MrXiaoM/qsign)默认支持pad协议，是带pad所需的签名文件的，但是本项目只默认携带了Android_PHONE签名所需的文件，所以本项目的[8.9.63](https://github.com/fuqiuluo/unidbg-fetch-qsign/tree/master/txlib/8.9.63)并不支持pad登陆，请勿混淆项目。下游项目[qsign](https://github.com/MrXiaoM/qsign)若可以成功签名则无需担心冻结风险。

**Comment by Dream-Rainy** [comment]
还有一点需要注意的是，就算pad协议使用phone的文件成功进行了签名，但是两边的库文件并不一致，可能会因为腾讯方面的检测而导致冻结及风控，请使用协议对应的文件进行签名

**Comment by dmlgzs** [comment]
> 还有一点需要注意的是，就算pad协议使用phone的文件成功进行了签名，但是两边的库文件并不一致，可能会因为腾讯方面的检测而导致冻结及风控，请使用协议对应的文件进行签名

你好。aPad 和 aPhone 文件是完全一样的。是同一个 apk，腾讯很早就合并了。

**Comment by Dream-Rainy** [comment]
> > 还有一点需要注意的是，就算pad协议使用phone的文件成功进行了签名，但是两边的库文件并不一致，可能会因为腾讯方面的检测而导致冻结及风控，请使用协议对应的文件进行签名
> 
> 你好。aPad 和 aPhone 文件是完全一样的。是同一个 apk，腾讯很早就合并了。

啊是这样的吗，那是我疏忽了。也就是说现在可以直接用同一份文件签名PHONE和PAD了吗

**Comment by arnann** [comment]
> > > > 还有一点需要注意的是，就算pad协议使用phone的文件成功进行了签名，但是两边的库文件并不一致，可能会因为腾讯方面的检测而导致冻结及风控，请使用协议对应的文件进行签名
> > > 
> > > 
> > > 你好。aPad 和 aPhone 文件是完全一样的。是同一个 apk，腾讯很早就合并了。
> > 
> > 
> > 啊是这样的吗，那是我疏忽了。也就是说现在可以直接用同一份文件签名PHONE和PAD了吗
> 
> 我一直这么干，我都干到8.9.78了都没事

8.9.78在哪里

**Comment by UlyssesZh** [comment]
8.9.71 用 ANDROID_PHONE 协议也被冻结了.

**Comment by HOursH** [comment]
换成8.9.73又开始报了：Failed to send message, your account may be blocked.
2023-09-15 10:11:27.042 | INFO     | graia.ariadne.model:log:82 - xxx: [SEND][[xxx] <- [图片]
2023-09-15 10:11:27.042 | WARNING  | graia.ariadne.app:send_group_message:1788 - Failed to send message, your account may be blocked.
昨天晚上还好好的，难不成是被盯上了吗

**Comment by fuqiuluo** [comment]
这些版本用了之前上报检测的检测点，之前是不封号，现在突然就封号了，一个bit位一但是1他就封号。估计是腾讯憋了一下，然后突然开始封号的，无奈于我的**天选4**主板烧了，有待修复。

**Comment by HOursH** [comment]
> 这些版本用了之前上报检测的检测点，之前是不封号，现在突然就封号了，一个bit位一但是1他就封号。估计是腾讯憋了一下，然后突然开始封号的，无奈于我的**天选4**主板烧了，有待修复。

所以你指的版本是qsign协议，列如：8.9.73，8.9.70，8.9.68，8.9.63都会触发，还是说fix-protocol-version版本？
还是说目前除了等更新，就没办法了吗？
问了一些人，他们的都还没封

**Comment by fuqiuluo** [comment]
已修复，1.3.0

**Comment by HOursH** [comment]
> 已修复，1.3.0

1.3.0是什么东西，没看懂
目前直接使用unidbg-fetch-qsignv1.1.9 并且qsign为8.9.73还会封吗

**Comment by arnann** [comment]
> > 已修复，1.3.0
> 
> 1.3.0是什么东西，没看懂 目前直接使用unidbg-fetch-qsignv1.1.9 并且qsign为8.9.73还会封吗

会 你有解决这个问题吗
