### ISSUE TITLE
运行一段时间异常

### ISSUE THREAD

**Issue by DeHby** [fuqiuluo/unidbg-fetch-qsign#259]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
unnable.java:30)                                                                        at java.lang.Thread.run(Unknown Source)                                 moe.fuqiuluo.api.SessionNotFoundError: Uin is not registered.                           at moe.fuqiuluo.api.SessionNotFoundError.<clinit>(exceptions.kt)                at moe.fuqiuluo.api.SessionKt.findSession(session.kt:18)                        at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invokeSuspend(request_token.kt:15)                                                                           at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invoke(request_token.kt)                                                                                     at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invoke(request_token.kt)                                                                                     at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)                                                                                   at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)              at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)              at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                                                               at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)                                                                          at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)                                                                          at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)                 at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)                    at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)                                                                                at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)           at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)           at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)                              at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)                                         at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)                                         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)                                                                     at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)                                                                               at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)                                                                               at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)                                                                   at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)                                                                                    at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)                                                                       at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)                                                                                 at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)                                                                                 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                   at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                   at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)                                            at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)                                                       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)                                                       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                             at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)                                           at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)                                                      at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)                                                      at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)                                                                  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)              at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)                                                                               at kotlinx.coroutines.BuildersKt.launch(Unknown Source)                         at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)                                                            at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)                                                     at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)                                                             at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)                                                                 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)                                                                       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)                                                                   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)                                                           at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)                 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)                                                                 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                    at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)                                                   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                        at java.lang.Thread.run(Unknown Source)                                 moe.fuqiuluo.api.SessionNotFoundError: Uin is not registered.                           at moe.fuqiuluo.api.SessionNotFoundError.<clinit>(exceptions.kt)                at moe.fuqiuluo.api.SessionKt.findSession(session.kt:18)                        at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invokeSuspend(request_token.kt:15)                                                                           at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invoke(request_token.kt)                                                                                     at moe.fuqiuluo.api.Request_tokenKt$requestToken$1.invoke(request_token.kt)                                                                                     at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)                                                                                   at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)              at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)              at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                                                               at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)                                                                          at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)                                                                          at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)                 at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)                    at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)                                                                                at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)           at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)           at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)                              at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)                                         at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)                                         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)                                                                     at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)                                                                               at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)                                                                               at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)                                                                   at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)                                                                                    at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)                                                                       at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)                                                                                 at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)                                                                                 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                   at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                   at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)                                            at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)                                                       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)                                                       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)                                                                                     at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)                                                                                   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)                                                                        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)                       at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)                             at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)                                        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)                                                                                 at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)                                           at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)                                                      at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)                                                      at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)                                                                  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)              at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)                                                                               at kotlinx.coroutines.BuildersKt.launch(Unknown Source)                         at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)                                                            at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)                                                     at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)                                                             at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)                                                                 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)                                                                       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)                                                                   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)                                                           at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)                 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)                                                                 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                    at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)                                                   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                        at java.lang.Thread.run(Unknown Source)

**Comment by ChihHao-Su** [comment]
我也遇到这个问题……

**Comment by w1ndseeker** [comment]
同样的问题，回退到1.1.7貌似暂时没出现这个bug

**Comment by jgeeee** [comment]
我这里最后是 at java.base/java.lang.Thread.run(Thread.java:833)，其他一致

**Comment by saltyplum** [comment]
> 我这里最后是 at java.base/java.lang.Thread.run(Thread.java:833)，其他一致

+1

**Comment by ikechan8370** [comment]
+1
