### ISSUE TITLE
java.lang.UnsupportedOperationException: android/content/pm/ApplicationInfo->nativeLibraryDir:Ljava/lang/String;

### ISSUE THREAD

**Issue by iPsychopath** [fuqiuluo/unidbg-fetch-qsign#55]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
qsign版本：`1.0.5`
系统版本：`CentOS Linux release 7.9.2009 (Core)`
运行时报错，但是不影响使用，能正常登陆。
```
[FEKit_]info: qq_sign.h:210 DispatchEvent cmd_event:Kicked
[FEKit_]error: device_info.h:177 jniGetAppVersionName:8.9.63
Jun 28, 2023 10:59:02 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /proc/meminfo
Jun 28, 2023 10:59:02 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/proc/meminfo, oflags=0x0, mode=0
Jun 28, 2023 10:59:02 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /proc/cpuinfo
Jun 28, 2023 10:59:02 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/proc/cpuinfo, oflags=0x0, mode=0
[FEKit_]info: device_info.h:533 533
[FEKit_]info: device_info.h:535 535
[FEKit_]info: device_info.h:537 537
Jun 28, 2023 10:59:02 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /proc/sys/kernel/random/boot_id
Jun 28, 2023 10:59:02 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/proc/sys/kernel/random/boot_id, oflags=0x0, mode=0
[FEKit_]info: device_token.h:246 begin pack
[FEKit_]info: device_token.h:248 pack buff result len:1138
[FEKit_]info: device_token.h:263 begin sendmessage : len :1138
Jun 28, 2023 10:59:03 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/base.apk
Jun 28, 2023 10:59:03 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/base.apk, oflags=0x0, mode=0
[FEKit_]error: o3_channel_encrypt.h:271 gen new channel
FEBound.transform(9D73115C95E7DCC9BB3D27388DC2E29CB3F65454C6177C818706FBB690062679) => C8806043B1E9C9604848802A54C85D59B5187242F5A9D944EA92C8C2AC8F1F1C
[FEKit_]error: o3_channel_encrypt.h:481 est check: a66d3a899b8773e6b0dc8af6ba145d2f0333522d96b4cb3e6b53c1cc0de51b38321176bbd9f727f55d2e4232dd3820dd
[FEKit_]error: ChannelManager.cpp:66 o3cm@S: getToken, trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey
uin = 879552973, id = 0, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey, data = 0A08676574546F6B656E122102C7F0B4EE1CC71C08B84A1A6B82DC9E700A2693B93D9042A8394519E30D6F3C9D22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652ABE091D97765622B25A121659869BA664AA823B24D5E6C111EF66FC749089AF28F8A370C98487FC5E947AD44D7D04556C64D3F5379E77E76A8E3288612BA2BCA110EF1122083D850EF9EB9EF0B9B5538DE11E14C41D9A6CE873BE7464E32F4209C859A3DD2224E110C6B7208C45E615731C92CC218080308B780BC51DE31CB406B1A081846977C876417E8B9074F1B4A30017054FB473C6F3E4FD429D2ACD6C97811511F8B8C730E6C44170C0FC537B88EF46E6EF92184BED657EC2B5DE5E36D0E1F87A1C3627515112897055D4633FF904397A9A635AA07356777ADE0E54AF3C7B6B1DE4D55284E9FC50B38D5F1431FA37EF6F324B33EF44993A92EE747BC13D87F4B02D2563724AED0631B7E80E75B628575874F198F5434265796AE4493298639369F8269B28E20F0176922004966E559A589B75F92E0DEF4083508B5A8CF62D049A654D2F1CC19DE2E1EEACF3ED210798762BD64A6C08119E8EDCD7B4AFAB28D842FC8C9AC2FEBDF299DDA076CEAB86A16BFDACDAE15388350923FB7C5943480853D783C696F49E25FA88F8102EFF2578202A30794A995823F0274BB8974E648AA2D762E5B38E7A16CFB2F3C619E7A7A002D57F348562A96117727AA23A6F63890726804F3E90BDAB2E45584D3709340E4EDCE7E11C525222E235A1E8CD44D48887B192D3EE0239BCC561D96B19B865D5D6419D45AD5619E09F92FADA5C2A18C98F96F33FBC1934FF4F4C193CF6868D3F4DBFC216C9A5DF5797ABC0FC5CF7B3529B32ABA14A3A7D7CBE68F91B97FF7259D6E80EB64D4A414376B26EA1B239854D6C682C4F209788899BB029DB89DA777AC1704E47063CE10A7EE2D06FD182F7C660EE59230C01D1ADB6EAD89049BA51F82E11B8756F3AFD1AF677445E51065878B1BBBB79EDC6576DBC4351384542FC5C67D5989824EEE5D5972CC02A876821C4021F0265DAA89242137CD521B0503612956A48D445F1073B1A58141E7D716AB2E8113036A52530087F4BD68E3BB9B400FC0BB21F20C462A5C62EA769945CA959CFA6099D5059AD87E28D8B9E588E4FE7C9867D6F94CA70BA12918CE2BB946B49EB344B05804C97C6EBFAF40D4478F9B42177DA877301052BEC8DFE76569CDE904E712DC4E6492288ACC5D3F468C2DD3E23BFB956020CE61C833D32E4B59DF436997134B014435D9F96AC644EF2151067A042A1D44CAE5395A44E0C4932082DF1E773F0231AB4B383409694982998E7A9FBFDC2ADB40153C8ADF4A15EF64B5CB67203589E8BB5FB45D4145C75D0086F541A4EA15B72E2896587A0E5CCA5BBF9FF675733EBDFEB00A5A50EAC6063C3FB73CD07D69F24668CDF0F9082819EFAD8B8E18C6C8A4D872B97E90941CD64C5114AB28DA24C7BC4B27470AF97E36CFE959F613BDE517F1DAC419B3FE79A0C5F4220B10790668E0C7A64408441B2722949021FFC1965F22A73CA306094F519219BD0C9AB2208FD32EC5EC9278E3D0973910E969076374FA8E93D368E49A2D6CD0A50328A51C3131AA39493D66ABED48C9875D666C32A30EF3D68B9B9A562A75BB759C730AE2C1AB0D2018EF9241064B5B2A2639FD09C526468BE59E7EBD9D629027100A2EEDDA8BB3463E7FA0D63D83FE9FB59C39CE56D4895DF6FB7721C663924E1340662907B44EF20AD8ECC77CA441119FF72788D78132B869071103CA4C39E02633EE7A3D99331DF9B2EFBA6AC0C32206FF553973DBE37A901434A0A4363A7CF8A0E21C8E38E047BA2B04D774A256A313A30A66D3A899B8773E6B0DC8AF6BA145D2F0333522D96B4CB3E6B53C1CC0DE51B38321176BBD9F727F55D2E4232DD3820DD)
[FEKit_]info: qq_sign.h:132 [GetSign] cmd:MessageSvc.PbSendMsg
uin = 879552973, id = -1, sendPacket(cmd = trpc.o3.report.Report.SsoReport, data = 0A0B306466303030373136343612610A1C56315F414E445F53515F382E392E36335F343138385F4844424D5F540A09362E3130302E3234380A0B7369676E5F7265706F72740A04686F73740A01300A203335626632306532613365323562663731353437396436616237366231343664)
FEBound.transform(E242010001957B8FA300099CF0817A36CB749D2DF8) => 4CF320A5223EDA463C951C602CAA42CB6389D70488
Jun 28, 2023 10:59:03 AM com.github.unidbg.linux.ARM64SyscallHandler hook
WARNING: handleInterrupt intno=2, NR=-129472, svcNumber=0x15b, PC=unidbg@0xfffe0644, LR=RX@0x40421168[libfekit.so]0xa1168, syscall=null
java.lang.UnsupportedOperationException: android/content/pm/ApplicationInfo->nativeLibraryDir:Ljava/lang/String;
        at com.github.unidbg.linux.android.dvm.AbstractJni.getObjectField(AbstractJni.java:171)
        at com.github.unidbg.linux.android.dvm.AbstractJni.getObjectField(AbstractJni.java:141)
        at com.github.unidbg.linux.android.dvm.DvmField.getObjectField(DvmField.java:126)
        at com.github.unidbg.linux.android.dvm.DalvikVM64$92.handle(DalvikVM64.java:1365)
        at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:118)
        at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
        at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:32)
        at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
        at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:78)
        at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:82)
        at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
        at com.github.unidbg.thread.BaseTask.continueRun(BaseTask.java:104)
        at com.github.unidbg.thread.ThreadTask.dispatch(ThreadTask.java:36)
        at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
        at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
        at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
        at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
        at com.github.unidbg.Module.emulateFunction(Module.java:163)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:48)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign$default(QQSecuritySign.kt:46)
        at moe.fuqiuluo.api.SignKt$configSign$2$sign$1.invoke(Sign.kt:72)
        at moe.fuqiuluo.api.SignKt$configSign$2$sign$1.invoke(Sign.kt:69)
        at moe.fuqiuluo.unidbg.QSecVMWorker.work(QSecVm.kt:26)
        at moe.fuqiuluo.unidbg.pool.FixedWorkPoolKt.work(FixedWorkPool.kt:126)
        at moe.fuqiuluo.api.SignKt$configSign$2.invokeSuspend(Sign.kt:69)
        at moe.fuqiuluo.api.SignKt$configSign$2.invoke(Sign.kt)
        at moe.fuqiuluo.api.SignKt$configSign$2.invoke(Sign.kt)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
        at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
        at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
        at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
        at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
        at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

Jun 28, 2023 10:59:03 AM com.github.unidbg.AbstractEmulator handleEmuException
WARNING: emulate RX@0x4018bf20[libc.so]0x1bf20 exception sp=RW@0x40dbe290, msg=android/content/pm/ApplicationInfo->nativeLibraryDir:Ljava/lang/String;, offset=9ms
[FEKit_]info: qq_sign.h:132 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey
FEBound.transform(6B39010001959DB1C5000AC5D03A2980E32A69BC99) => A3DB20A5223E46E4D495128C7CED13E3456F5163BA
Receive (trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey) Data => size = 153 data: 0A940130BABAAAE1D24202DD2010470FD6DD8184A3C97C108E995DD0EF145E1A2E1EEA90BDE141635B647449C20D130652088821CAAE1BEE3B2086DCBB33E9AF307EBE1703ACD3F2B410C3F34A726A3C0809247D594DB5AFFFFF9EDFD69F6FF661A1E8287A6418E9FEF4E7AA63D11A37806496B1CD90603177A23E9E733D2C7172058F00352F015FAE9DB58F42F8337A95F50A72DE46FB1000
[FEKit_]info: ChannelManager.cpp:91 origin cmd:getToken ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey
[FEKit_]error: ChannelManager.cpp:94 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey bcmd:getToken
[FEKit_]info: task_handle.h:74 TaskSystem not allow
[FEKit_]info: device_token.h:285 response len :20
[FEKit_]info: device_token.h:308 DeviceToken::saveToken ok! expireTime:1688007543
```

**Comment by fuqiuluo** [comment]
1.1.0修复
