### ISSUE TITLE
Windows下运行.bat文件报错

### ISSUE THREAD

**Issue by why0209** [fuqiuluo/unidbg-fetch-qsign#7]
大佬们，直接运行.bat时出现这个错误，是少参数了吗。

Exception in thread "main" java.lang.IllegalArgumentException: Lack of server.port.
        at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
        at MainKt.main(Main.kt:44)

**Comment by hezi-biancheng** [comment]
我只想说我到现在还没有下载好，下载到一半就下不动了。

**Comment by kagangtuya-star** [comment]
端口号的参数貌似没填或者填错了

**Comment by Special-Week** [comment]
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/87489040/e3916492-d44c-4791-be11-a63aac4c1fa2)
仅供参考

**Comment by fuqiuluo** [comment]
端口参数没填
