### ISSUE TITLE
程序崩溃 线程安全问题？

### ISSUE THREAD

**Issue by WorldLeen** [fuqiuluo/unidbg-fetch-qsign#75]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
因为这个程序没有日志文件，所以只有这一部分报错信息：
```

        at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
        at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "DefaultDispatcher-worker-4" java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
        at java.base/java.util.ArrayList$Itr.remove(ArrayList.java:1011)
        at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:182)
        at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
        at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
        at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
        at com.github.unidbg.Module.emulateFunction(Module.java:163)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
        at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:52)
        at com.tencent.mobileqq.channel.ChannelManager.onNativeReceive(ChannelManager.kt:24)
        at moe.fuqiuluo.unidbg.env.QSecJni$callVoidMethodV$1.onReceive(QSecJni.kt:75)
        at moe.fuqiuluo.net.Handler.submitPacket(PacketHandler.kt:56)
        at moe.fuqiuluo.net.PacketHandler.invoke(PacketHandler.kt:86)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1$1.invoke(SimpleClient.kt:58)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1$1.invoke(SimpleClient.kt:57)
        at moe.fuqiuluo.net.DecoderKt.decodePacket(Decoder.kt:85)
        at moe.fuqiuluo.net.DecoderKt.decode(Decoder.kt:56)
        at moe.fuqiuluo.net.SimpleClient$initConnection$1.invokeSuspend(SimpleClient.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(selector), StandaloneCoroutine{Cancelling}@2853349a, Dispatchers.IO]
```

**Comment by WorldLeen** [comment]
看起来这东西并不是线程安全的，要不加个锁？

**Comment by fuqiuluo** [comment]
我已经加锁了的，真是奇怪呢这个东西

**Comment by WorldLeen** [comment]
> 我已经加锁了的，真是奇怪呢这个东西

`com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:182)`
根据报错信息，很明显可以看到这个线程安全问题并非来自于腾讯的代码，而是来自于unidbg这个lib
也就是说unidbg是完全不支持多线程的
这就是指，锁可能没有加干净，应该加全局锁在任何涉及到unidbg调用的地方
包括但不限于sign、energy，而且应该是全局锁，保证整个程序同时只会有一个地方在使用unidbg lib

这样试试看？

**Comment by WorldLeen** [comment]
> 我已经加锁了的，真是奇怪呢这个东西

刚才又崩了，崩溃日志一样
我已经给我的程序加锁了，确保同时只会有一个HTTP请求给这个服务器，但还是会有这个崩溃错误，这太奇怪了
而且最奇怪的是，崩溃之后进程不会自己结束，我还没法用脚本自动拉起

**Comment by WorldLeen** [comment]
> 我已经加锁了的，真是奇怪呢这个东西

而且我好像已经发现错误点了，需要将这两行代码调换一下顺序应该就好了。
`        reentrantLock.unlock()
        this.dataListener?.onReceive(from)`

**Comment by WorldLeen** [comment]
> 我已经加锁了的，真是奇怪呢这个东西

对代码进行修改重新构建后，确认签名服务器依然可以正常工作
同时截止到目前为止，没有再出现此崩溃问题，可以认为此bug已经得到了修复
此bug的修复PR已经发布，请合并吧 XD
